In [1]:
import pandas as pd

df = pd.read_csv("data/processed/menu_metrics.csv")
df.head()

,item_id,item_name,category,price,prep_time_minutes,units_sold_last_month,profit_margin_percent,COGS,revenue,profit
0,101,Garlic Knots,Appetizers,8.99,5,159,46,10.87,1429.41,657.5286
1,102,Loaded Fries,Appetizers,12.50,8,490,38,4.49,6125.00,2327.5000
2,103,Bruschetta,Appetizers,10.50,6,46,43,12.32,483.00,207.6900
3,104,Stuffed Mushrooms,Appetizers,11.00,7,62,64,6.36,682.00,436.4800
4,105,Buffalo Wings,Appetizers,13.50,9,361,75,15.86,4873.50,3655.1250

In [2]:
HIGH_SALES_THRESHOLD = df["units_sold_last_month"].quantile(0.6)
LOW_MARGIN_THRESHOLD = 50     # percent
LONG_PREP_THRESHOLD = 12      # minutes

In [3]:
df.sort_values("profit", ascending=False).head(3)[
    ["item_name", "profit"]
]

          item_name    profit
10     Steak Frites  11022.48
13  Chicken Alfredo   8874.36
18   Seafood Paella   8527.50

In [4]:
df[
    (df["units_sold_last_month"] >= HIGH_SALES_THRESHOLD) &
    (df["profit_margin_percent"] < LOW_MARGIN_THRESHOLD)
][["item_name", "units_sold_last_month", "profit_margin_percent"]]

           item_name  units_sold_last_month  profit_margin_percent
1       Loaded Fries                    490                     38
7   Mini Quesadillas                    420                     40
12    Grilled Salmon                    379                     45
29        Lemon Tart                    460                     40
33    Fresh Lemonade                    383                     49
39      Orange Juice                    448                     41
42    House Iced Tea                    401                     40

In [5]:
df[df["prep_time_minutes"] >= LONG_PREP_THRESHOLD][
    ["item_name", "prep_time_minutes"]
].sort_values("prep_time_minutes", ascending=False)

               item_name  prep_time_minutes
21            Lamb Chops                 20
16              BBQ Ribs                 18
18        Seafood Paella                 17
10          Steak Frites                 15
12        Grilled Salmon                 14
13       Chicken Alfredo                 13
20      Thai Green Curry                 13
14      Mushroom Risotto                 12
19  Paneer Butter Masala                 12

In [6]:
df["popularity_tier"] = df["units_sold_last_month"].apply(
    lambda x: "High" if x >= HIGH_SALES_THRESHOLD else "Low"
)

df["profitability_tier"] = df["profit"].apply(
    lambda x: "High" if x >= df["profit"].median() else "Low"
)

df["menu_class"] = df["popularity_tier"] + "-" + df["profitability_tier"]

In [7]:
df[["item_name", "menu_class"]].head()

           item_name menu_class
0       Garlic Knots    Low-Low
1       Loaded Fries  High-High
2         Bruschetta    Low-Low
3  Stuffed Mushrooms    Low-Low
4      Buffalo Wings  High-High

In [9]:
df.to_csv("data/processed/menu_metrics.csv", index=True)